version: '3'

services:
  frontend:
    image: nginx:alpine
    container_name: stream-frontend
    ports:
      - "8080:80"
    volumes:
      - ../frontend:/usr/share/nginx/html
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: unless-stopped
  api:
    build:
      context: ../
      dockerfile: api/Dockerfile
    container_name: stream-api
    ports:
      - "3000:3000"
    volumes:
      - ../data:/data
      - ../media:/media
    environment:
      - PORT=3000
      - DB_PATH=/data/streaming.db
      - MEDIA_PATH=/media
      - SECRET_KEY=changeme_in_production
    depends_on:
      - valkey
    restart: unless-stopped
  rtmp:
    image: tiangolo/nginx-rtmp
    container_name: stream-rtmp
    ports:
      - "1935:1935"  # RTMP port
      - "8081:80"    # HLS access port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../media:/media
    depends_on:
      - api
    restart: unless-stopped
  valkey:
    image: valkey/valkey:latest
    container_name: stream-valkey
    ports:
      - "6379:6379"
    volumes:
      - ../data/valkey:/data
    restart: unless-stopped
# I might not need it
  minio:
    image: minio/minio
    container_name: stream-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../data/minio:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  data:
  media: